name: variantcalling
channels:
  - bioconda
  - conda-forge
dependencies:
  - bwa-mem2
  - samtools
  - lofreq
  - bcftools>=1.22
  - python>=3.11
  - pandas
  - fastp
  - fastqc
  - multiqc
  - htslib>=1.17
  - tabix
  - snpeff=5.2
  - openjdk=17
  - scipy
  - matplotlib
  - seaborn
  - pip
  - pip:
      - cyvcf2>=0.30.28
      - gprofiler-official>=1.0.0
